map = """
.
. . s50
. #
. #
. # .   # # #
. # .   . . #
. # #   # . #
. . .   # . .
. . .   # # #
"""

[[entities]]
sid = 0
state = 0
[entities.ai.AddAvailableSquare]
[entities.blocking.Movement]
[entities.coords]
x = 1
y = 2
[entities.decision_timer]
time = 3
reset = 4
